// swift-tools-version: 5.9
// Default Package.swift - will be regenerated by buildAppIos.js based on config
// This minimal version allows Xcode to open the project without resolving Firebase
import PackageDescription

// TODO: haven't made this conditional yet
let package = Package(
    name: "iosnativeWebView",
    platforms: [.iOS(.v17), .macOS(.v13)],
    products: [
        .library(name: "CatalystCore", targets: ["CatalystCore"])
    ],
    dependencies: [
        .package(path: "CoreLogic"),
        .package(url: "https://github.com/kylef/JSONSchema.swift", from: "0.6.0"),
        .package(url: "https://github.com/google/GoogleSignIn-iOS", from: "7.0.0")
    ],
    targets: [
        // Core functionality (WebView, bridge, utils, constants)
        // App-level files (AppDelegate, ContentView, etc.) are in iosnativeWebView/ directory
        .target(
            name: "CatalystCore",
            dependencies: [
                .product(name: "CatalystCoreLogic", package: "CoreLogic"),
                .product(name: "JSONSchema", package: "JSONSchema.swift"),
                .product(name: "GoogleSignIn", package: "GoogleSignIn-iOS")
            ],
            path: "Sources/Core"
        )
        // Note: no .testTarget here for CatalystCore's own simulator-based tests
        // (iosnativeWebViewTests) — those are declared and run via the Xcode
        // project/scheme, not `swift test` at this package root. The
        // CatalystCoreLogicTests test target lives in the nested CoreLogic/
        // package (see CoreLogic/Package.swift) so `swift test --package-path
        // CoreLogic` can run with zero simulator, zero remote dependency
        // resolution.
    ]
)
