export const mappingScenarios = [
    {
        code: "RUNTIME-NATIVE-001",
        title: "Native string 'permission denied' maps to RUNTIME-NATIVE-001",
        tier: "mapping",
        kind: "mapping",
        nativeError: "permission denied",
        expect: { code: "RUNTIME-NATIVE-001", docSubstr: "RUNTIME-NATIVE/RUNTIME-NATIVE-001" },
    },
    {
        code: "RUNTIME-NATIVE-002",
        title: "Native code RUNTIME-NATIVE-002 (Permission required) error mapping",
        tier: "mapping",
        kind: "mapping",
        createCode: "RUNTIME-NATIVE-002",
        expect: { code: "RUNTIME-NATIVE-002", docSubstr: "RUNTIME-NATIVE/RUNTIME-NATIVE-002" },
    },
    {
        code: "RUNTIME-NATIVE-003",
        title: "Native string 'network unavailable' maps to RUNTIME-NATIVE-003",
        tier: "mapping",
        kind: "mapping",
        nativeError: "network unavailable",
        expect: { code: "RUNTIME-NATIVE-003", docSubstr: "RUNTIME-NATIVE/RUNTIME-NATIVE-003" },
    },
    {
        code: "RUNTIME-NATIVE-004",
        title: "Native code RUNTIME-NATIVE-004 (Download failed) error mapping",
        tier: "mapping",
        kind: "mapping",
        createCode: "RUNTIME-NATIVE-004",
        expect: { code: "RUNTIME-NATIVE-004", docSubstr: "RUNTIME-NATIVE/RUNTIME-NATIVE-004" },
    },
    {
        code: "RUNTIME-NATIVE-005",
        title: "Native string 'file not found' maps to RUNTIME-NATIVE-005",
        tier: "mapping",
        kind: "mapping",
        nativeError: "file not found",
        expect: { code: "RUNTIME-NATIVE-005", docSubstr: "RUNTIME-NATIVE/RUNTIME-NATIVE-005" },
    },
    {
        code: "RUNTIME-NATIVE-006",
        title: "Native code RUNTIME-NATIVE-006 (File too large) error mapping",
        tier: "mapping",
        kind: "mapping",
        createCode: "RUNTIME-NATIVE-006",
        expect: { code: "RUNTIME-NATIVE-006", docSubstr: "RUNTIME-NATIVE/RUNTIME-NATIVE-006" },
    },
    {
        code: "RUNTIME-NATIVE-007",
        title: "Native string 'storage full' maps to RUNTIME-NATIVE-007",
        tier: "mapping",
        kind: "mapping",
        nativeError: "storage full",
        expect: { code: "RUNTIME-NATIVE-007", docSubstr: "RUNTIME-NATIVE/RUNTIME-NATIVE-007" },
    },
    {
        code: "RUNTIME-NATIVE-008",
        title: "Native code RUNTIME-NATIVE-008 (File corrupted) error mapping",
        tier: "mapping",
        kind: "mapping",
        createCode: "RUNTIME-NATIVE-008",
        expect: { code: "RUNTIME-NATIVE-008", docSubstr: "RUNTIME-NATIVE/RUNTIME-NATIVE-008" },
    },
    {
        code: "RUNTIME-NATIVE-009",
        title: "Native string 'operation cancelled' maps to RUNTIME-NATIVE-009",
        tier: "mapping",
        kind: "mapping",
        nativeError: "operation cancelled",
        expect: { code: "RUNTIME-NATIVE-009", docSubstr: "RUNTIME-NATIVE/RUNTIME-NATIVE-009" },
    },
    {
        code: "RUNTIME-NATIVE-010",
        title: "Native code RUNTIME-NATIVE-010 (No file selected) error mapping",
        tier: "mapping",
        kind: "mapping",
        createCode: "RUNTIME-NATIVE-010",
        expect: { code: "RUNTIME-NATIVE-010", docSubstr: "RUNTIME-NATIVE/RUNTIME-NATIVE-010" },
    },
    {
        code: "RUNTIME-NATIVE-011",
        title: "Native code RUNTIME-NATIVE-011 (Invalid file type) error mapping",
        tier: "mapping",
        kind: "mapping",
        createCode: "RUNTIME-NATIVE-011",
        expect: { code: "RUNTIME-NATIVE-011", docSubstr: "RUNTIME-NATIVE/RUNTIME-NATIVE-011" },
    },
    {
        code: "RUNTIME-NATIVE-012",
        title: "Native code RUNTIME-NATIVE-012 (Invalid parameters) error mapping",
        tier: "mapping",
        kind: "mapping",
        createCode: "RUNTIME-NATIVE-012",
        expect: { code: "RUNTIME-NATIVE-012", docSubstr: "RUNTIME-NATIVE/RUNTIME-NATIVE-012" },
    },
    {
        code: "RUNTIME-NATIVE-015",
        title: "Native unrecognized error string maps to RUNTIME-NATIVE-015 (Internal error)",
        tier: "mapping",
        kind: "mapping",
        nativeError: "some unknown native failure",
        expect: { code: "RUNTIME-NATIVE-015", docSubstr: "RUNTIME-NATIVE/RUNTIME-NATIVE-015" },
    },
    {
        code: "RUNTIME-NATIVE-016",
        title: "Native string 'camera unavailable' maps to RUNTIME-NATIVE-016",
        tier: "mapping",
        kind: "mapping",
        nativeError: "camera unavailable",
        expect: { code: "RUNTIME-NATIVE-016", docSubstr: "RUNTIME-NATIVE/RUNTIME-NATIVE-016" },
    },
    {
        code: "RUNTIME-NATIVE-017",
        title: "Native string 'camera in use' maps to RUNTIME-NATIVE-017",
        tier: "mapping",
        kind: "mapping",
        nativeError: "camera in use",
        expect: { code: "RUNTIME-NATIVE-017", docSubstr: "RUNTIME-NATIVE/RUNTIME-NATIVE-017" },
    },
]

export default mappingScenarios
