// swift-tools-version: 5.9
// Default Package.swift - will be regenerated by buildAppIos.js based on config
// This minimal version allows Xcode to open the project without resolving Firebase
import PackageDescription

// TODO: haven't made this conditional yet
let package = Package(
    name: "iosnativeWebView",
    platforms: [.iOS(.v17)],
    products: [
        .library(name: "CatalystCore", targets: ["CatalystCore"])
    ],
    dependencies: [
        .package(url: "https://github.com/kylef/JSONSchema.swift", from: "0.6.0"),
        .package(url: "https://github.com/google/GoogleSignIn-iOS", from: "7.0.0")
    ],
    targets: [
        // Core functionality (WebView, bridge, utils, constants)
        // App-level files (AppDelegate, ContentView, etc.) are in iosnativeWebView/ directory
        .target(
            name: "CatalystCore",
            dependencies: [
                .product(name: "JSONSchema", package: "JSONSchema.swift"),
                .product(name: "GoogleSignIn", package: "GoogleSignIn-iOS")
            ],
            path: "Sources/Core"
        )
    ]
)
